In [3]:
import anthropic

client = anthropic.Anthropic()

message = client.messages.create(
  model="claude-haiku-4-5-20251001",
  max_tokens=1024,
  messages=[{
    "role": "user",
    "content": "Hello, Claude"
  }]
)
for block in message.content:
    if block.type == "text":
        print(block.text)

Hello! It's nice to meet you. How can I help you today?

In [1]:
excel = r"C:\Users\irahu\git_workspace\procurement-and-cost-estimation\data\bidders_details\ADNOC Approved Vendor List as of 10.12.2025.xlsx"

In [3]:
import pandas as pd

In [6]:
_df = pd.read_excel(excel, sheet_name="Sheet1")

In [5]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [7]:
_df

,Product Group Number,Product Group Description,Vendor Number,Vendor Name,Manufacture Number,Manufacture name,Manufacture Country,Remarks
0,122010,A/C UNITS – SPLIT & WINDOW,10000238,SYSTEMS EQUIPMENT L.L.C-O.P.C,20002132.0,AXIS SOLUTIONS PVT LTD,India,NaN
1,122010,A/C UNITS – SPLIT & WINDOW,10000101,U.T.S CARRIER LLC,20007034.0,CARRIER INTERNATIONAL CORPORATION,United States of America,Migrated
2,122010,A/C UNITS – SPLIT & WINDOW,10007311,S K M AIR CONDITIONING - L L C,20001799.0,SKM AIR CONDITIONING EQUIPMENT,United Arab Emirates,Migrated-SQM
3,122010,A/C UNITS – SPLIT & WINDOW,10000255,EMIRATES LINK TECHNOLOGY LLC,20009282.0,WAROM TECHNOLOGY INCORPORATED COMPA,China,NaN
4,122010,A/C UNITS – SPLIT & WINDOW,10000149,AL YASEAH OIL & GAS INDUSTRY SUPPLI,20020456.0,Wozair Limited,United Kingdom,NaN
...,...,...,...,...,...,...,...,...
18027,900085,OEM OPERATIONAL SPARES,10000550,DESCON AUTOMATION CONTROL SYSTEM LL,20001194.0,ODS METERING SYSTEMS B.V.,Netherlands,NaN
18028,900085,OEM OPERATIONAL SPARES,10000167,DOME OILFIELD ENGINEERING & SERVICE,20010493.0,COFIMCO,Italy,Migrated
18029,900085,OEM OPERATIONAL SPARES,10081413,THOR MIDDLE EAST L.L.C - BRANCH OF,20000966.0,PARKER MIDDLE EAST FZE,United Arab Emirates,NaN
18030,900085,OEM OPERATIONAL SPARES,10013348,Alucor Limited,NaN,( LOCAL MANUFACTURE ),NaN,WS205072896
18031,900085,OEM OPERATIONAL SPARES,10067491,ACEKROFT ENERGY SOLUTIONS- L.L.C,20001849.0,MCT BRATTBERG A.B.,Sweden,NaN

In [8]:
_df.tail(5)

,Product Group Number,Product Group Description,Vendor Number,Vendor Name,Manufacture Number,Manufacture name,Manufacture Country,Remarks
18027,900085,OEM OPERATIONAL SPARES,10000550,DESCON AUTOMATION CONTROL SYSTEM LL,20001194.0,ODS METERING SYSTEMS B.V.,Netherlands,NaN
18028,900085,OEM OPERATIONAL SPARES,10000167,DOME OILFIELD ENGINEERING & SERVICE,20010493.0,COFIMCO,Italy,Migrated
18029,900085,OEM OPERATIONAL SPARES,10081413,THOR MIDDLE EAST L.L.C - BRANCH OF,20000966.0,PARKER MIDDLE EAST FZE,United Arab Emirates,NaN
18030,900085,OEM OPERATIONAL SPARES,10013348,Alucor Limited,NaN,( LOCAL MANUFACTURE ),NaN,WS205072896
18031,900085,OEM OPERATIONAL SPARES,10067491,ACEKROFT ENERGY SOLUTIONS- L.L.C,20001849.0,MCT BRATTBERG A.B.,Sweden,NaN